---
- name: Launch proxy container
  docker_container:
    name: httptp1
    image: sylvainchu/tp-devops-http:0.0.15
    state: started
    pull: yes
    ports:
      - "80:80" 
      - "8080:8081"
    networks:
      - name: proxy_app_network
    container_default_behavior: compatibility
    networks_cli_compatible: no