---
- name: Launch application container
  docker_container:
    name: backtp1
    image: sylvainchu/tp-devops-backend:latest 
    state: started
    pull: yes
    env_file: /home/admin/.env
    networks:
      - name: app_database_network
      - name: proxy_app_network
    container_default_behavior: compatibility
    networks_cli_compatible: no