---
- name: Deploy application with Docker
  hosts: all
  become: true

  roles:
    # - install_docker
    - copy_env_file 
    - create_network
    - launch_database
    - launch_app
    - launch_proxy
