name: CI/CD DevOps 2025 - Build and Push Docker Images

on:
  push:
    branches:
      - develop
      - main
  # workflow_run:
  #   workflows: ["CI/CD DevOps 2025 - Test Backend"]  # Spécifie le nom du workflow précédent
  #   types:
  #     - completed
  #   branches:
  #     - main
  #     - develop

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'develop'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from pom.xml
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f TD1/backend/pom.xml)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./TD1/backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:${{ env.VERSION }}
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: ./TD1/db
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-db:${{ env.VERSION }}
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
          context: ./TD1/http
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-http:${{ env.VERSION }}
          push: true

      - name: Build and push front image
        uses: docker/build-push-action@v3
        with:
          context: ./TD1/front
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-front:${{ env.VERSION }}
          push: true