name: CI/CD DevOps 2025

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build and test with Maven
        run: |
          cd TD1/backend
          mvn clean install

  build-and-push-docker-images:
    needs: test-backend 
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout reposcodeitory
        uses: actions/checkout@v4

      - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./TD1/backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: ./TD1/db
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-db:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
          context: ./TD1/http
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-http:latest
          push: ${{ github.ref == 'refs/heads/main' }}
